"""Add User model and link to Portfolio

Revision ID: 24183b7f2a2d
Revises: 002_versioning
Create Date: 2026-02-12 23:38:25.243468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24183b7f2a2d'
down_revision: Union[str, None] = '002_versioning'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)

    with op.batch_alter_table('portfolio_versions', schema=None) as batch_op:
        batch_op.alter_column('version_state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'COMMITTED', name='versionstate'),
               existing_nullable=False,
               existing_server_default=sa.text("'committed'"))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('AI', 'USER_MANUAL', 'AI_REFINEMENT', name='versioncreatedby'),
               existing_nullable=False)
        # SQLite batch mode handles FKs automatically, and we don't have names for them
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'portfolios', ['portfolio_id'], ['id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        # batch_op.drop_index('idx_portfolio_slug')
        # batch_op.create_index('idx_portfolio_slug', ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key('fk_portfolios_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_portfolios_current_version_id', 'portfolio_versions', ['current_version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_portfolios_slug'))
        batch_op.drop_index('idx_portfolio_slug')
        batch_op.create_index('idx_portfolio_slug', ['slug'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('portfolio_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_by',
               existing_type=sa.Enum('AI', 'USER_MANUAL', 'AI_REFINEMENT', name='versioncreatedby'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('version_state',
               existing_type=sa.Enum('DRAFT', 'COMMITTED', name='versionstate'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'committed'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_github_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
