"""add_user_and_auth

Revision ID: 874d04192ae1
Revises: 002_versioning
Create Date: 2026-02-13 06:27:40.617249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874d04192ae1'
down_revision: Union[str, None] = '002_versioning'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.add_column('portfolios', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.drop_index('idx_portfolio_slug', table_name='portfolios')
    op.create_index('idx_portfolio_slug', 'portfolios', ['slug'], unique=False)
    op.create_index(op.f('ix_portfolios_slug'), 'portfolios', ['slug'], unique=True)
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'portfolios', 'portfolio_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_index(op.f('ix_portfolios_slug'), table_name='portfolios')
    op.drop_index('idx_portfolio_slug', table_name='portfolios')
    op.create_index('idx_portfolio_slug', 'portfolios', ['slug'], unique=True)
    op.drop_column('portfolios', 'user_id')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
